name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master


jobs:
  job_build:
    name: Compilation
    strategy:
      matrix:
        include:
          - model: nanos
            SDK: "$NANOS_SDK"
          - model: nanox
            SDK: "$NANOX_SDK"
          - model: nanosp
            SDK: "$NANOSP_SDK"

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: |
          make DEBUG=0 COIN=avian BOLOS_SDK=${{ matrix.SDK }} && mv bin/ avian-bin/

      - name: Upload Avian app binary
        uses: actions/upload-artifact@v2
        with:
          name: avian-app-${{ matrix.model }}
          path: avian-bin
